package edge

import (
	"context"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
)

// Caddy manages a `caddy run` subprocess with a generated Caddyfile.
// The binary must be built with the layer4 module:
//
//	xcaddy build --with github.com/mholt/caddy-l4
//
// Caddy owns public :443 via a layer4 SNI split (derp host → derper,
// everything else → its own HTTPS on localhost) and :80 for ACME
// challenges (derper answers its own HTTP-01 through a proxied route)
// plus the catch-all 404.
type Caddy struct {
	Bin       string // caddy binary (with caddy-l4)
	AdminAPI  string // e.g. 127.0.0.1:2019
	HTTPSAddr string // localhost HTTPS behind the layer4 split, e.g. 127.0.0.1:24443
	Derper    string // derper backend (plaintext), e.g. 127.0.0.1:18443
	FilePath  string // generated Caddyfile path

	mu  sync.Mutex
	cmd *exec.Cmd
}

// Expose is one public web route: Host → localhost bridge port.
type Expose struct {
	Host string // e.g. next.pairmesh.example (exact; Caddy handles wildcard certs)
	To   string // e.g. 127.0.0.1:13000
}

// Render writes the Caddyfile: layer4 SNI split on :443, admin on loopback,
// pairing API route, exposes with hardened headers + X-Forwarded-For,
// unknown hosts → 404 (no default backend).
//
// HTTPS sites bind HTTPSAddr explicitly (e.g. https://host:24443) so the
// http app never grabs :443 from the layer4 app. SNI and Host survive the
// raw-byte proxy untouched, so routing and cert selection just work.
func (c *Caddy) Render(domain, email, adminBackend string, exposes []Expose) error {
	derpHost := "derp." + domain
	var b strings.Builder
	// Header doubles as the drift anchor: deploy/Caddyfile.tmpl is
	// byte-identical to Render("example.com", ...) output (see test).
	// No blank line before `{`: `caddy fmt`-clean, so reloads log no warning.
	b.WriteString("# Generated by pms — do not hand-edit.\n# Requires caddy WITH github.com/mholt/caddy-l4.\n")
	fmt.Fprintf(&b, "{\n\tadmin %s\n\temail %s\n", c.AdminAPI, email)
	b.WriteString("\tlayer4 {\n\t\t:443 {\n")
	fmt.Fprintf(&b, "\t\t\t@derp tls sni %s\n", derpHost)
	b.WriteString("\t\t\troute @derp {\n\t\t\t\ttls\n")
	fmt.Fprintf(&b, "\t\t\t\tproxy tcp/%s\n", c.Derper)
	b.WriteString("\t\t\t}\n\t\t\troute {\n")
	fmt.Fprintf(&b, "\t\t\t\tproxy tcp/%s\n", c.HTTPSAddr)
	b.WriteString("\t\t\t}\n\t\t}\n")
	// QUIC/H3 rides UDP and derper never speaks it, so no SNI split is
	// needed: blind-proxy UDP 443 at Caddy's own H3 listener (which it
	// enables automatically on every TLS site). Without this block UDP
	// 443 answers nothing despite the H3 listener existing. NOTE the
	// address syntax: network prefix FIRST (`udp/:443`); `:443/udp`
	// adapts cleanly but fails at runtime with "unknown network".
	fmt.Fprintf(&b, "\t\tudp/:443 {\n\t\t\troute {\n\t\t\t\tproxy udp/%s\n\t\t\t}\n\t\t}\n\t}\n}\n\n", c.HTTPSAddr)
	fmt.Fprintf(&b, "https://%s:%s {\n\ttls {\n\t\tprotocols tls1.3\n\t}\n\thandle /_pms/* {\n\t\treverse_proxy %s\n\t}\n\trespond \"not found\" 404\n}\n\n",
		"pair."+domain, portOf(c.HTTPSAddr), adminBackend)
	// derp's TLS is terminated above by the layer4 `tls` handler, which uses
	// the TLS app cache: this unreachable dummy site exists only to drive
	// automation for the name.
	fmt.Fprintf(&b, "https://%s:%s {\n\ttls {\n\t\tprotocols tls1.3\n\t}\n\trespond \"not found\" 404\n}\n\n",
		"derp."+domain, portOf(c.HTTPSAddr))
	for _, e := range exposes {
		fmt.Fprintf(&b, "https://%s:%s {\n", e.Host, portOf(c.HTTPSAddr))
		b.WriteString("\ttls {\n\t\tprotocols tls1.3\n\t}\n")
		b.WriteString("\tencode gzip\n")
		fmt.Fprintf(&b, "\treverse_proxy %s {\n", e.To)
		b.WriteString("\t\theader_up X-Forwarded-For {remote_host}\n")
		b.WriteString("\t\theader_up X-Forwarded-Proto {scheme}\n")
		b.WriteString("\t\theader_up X-Real-IP {remote_host}\n")
		b.WriteString("\t}\n")
		b.WriteString("\theader {\n\t\t-Server\n\t}\n}\n\n")
	}
	// Catch-all with no backend (Host allowlist enforced).
	b.WriteString(":80 {\n\trespond \"not found\" 404\n}\n")
	if err := os.MkdirAll(filepath.Dir(c.FilePath), 0o700); err != nil {
		return err
	}
	return os.WriteFile(c.FilePath, []byte(b.String()), 0o600)
}

// portOf extracts the port from a host:port address.
func portOf(addr string) string {
	_, port, err := net.SplitHostPort(addr)
	if err != nil {
		return "443"
	}
	return port
}

// Start launches caddy run (restart-safe: kills previous instance first).
func (c *Caddy) Start(ctx context.Context) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.stopLocked()
	cmd := exec.CommandContext(ctx, c.Bin, "run", "--config", c.FilePath, "--adapter", "caddyfile")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("edge: start caddy: %w (need our caddy+l4 build on PATH as %q?)", err, c.Bin)
	}
	c.cmd = cmd
	return nil
}

// Reload graceful-reloads after Render.
func (c *Caddy) Reload() error {
	c.mu.Lock()
	bin, file := c.Bin, c.FilePath
	c.mu.Unlock()
	cmd := exec.Command(bin, "reload", "--config", file, "--adapter", "caddyfile")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("edge: caddy reload: %w: %s", err, out)
	}
	return nil
}

// Stop terminates the subprocess.
func (c *Caddy) Stop() {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.stopLocked()
}

func (c *Caddy) stopLocked() {
	if c.cmd != nil && c.cmd.Process != nil {
		_ = c.cmd.Process.Signal(os.Interrupt)
		_, _ = c.cmd.Process.Wait()
		c.cmd = nil
	}
}
